### ISSUE TITLE
java.util.ConcurrentModificationException happening in logs for botland code

### ISSUE THREAD

**Issue by OtherBrand** [OtherBrand/FFTB_Viewer#24]
java.util.ConcurrentModificationException: null
        at java.base/java.util.Vector$Itr.checkForComodification(Vector.java:1320)
        at java.base/java.util.Vector$Itr.next(Vector.java:1276)
        at fft_battleground.botland.bot.DataBetBot.generatePlayerRecordMap(DataBetBot.java:127)
        at fft_battleground.botland.bot.DataBetBot.init(DataBetBot.java:139)
        at fft_battleground.botland.BetterBetBot.call(BetterBetBot.java:58)
        at fft_battleground.botland.BotLand.run(BotLand.java:75)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by OtherBrand** [comment]
Should be resolved  as of 1.5.7

**Comment by OtherBrand** [comment]
It came back :(

**Comment by OtherBrand** [comment]
Looks like the issue was with the Vector Iterator.  It didn't like being accessed by multiple threads.

So I'm instead making my own copy of the Vector to get around this.
