### ISSUE TITLE
Illegal Argument exception when generating top ten players

### ISSUE THREAD

**Issue by OtherBrand** [OtherBrand/FFTB_Viewer#41]
java.lang.IllegalArgumentException: value already present: 1012 at com.google.common.collect.HashBiMap.put(HashBiMap.java:289) at com.google.common.collect.HashBiMap.put(HashBiMap.java:270) at java.base/java.util.AbstractMap.putAll(AbstractMap.java:281) at fft_battleground.dump.DumpReportsService.getTopPlayers(DumpReportsService.java:205) at fft_battleground.dump.DumpReportsService.generatePlayerLeaderboardData(DumpReportsService.java:246) at fft_battleground.dump.DumpReportsService.writeLeaderboard(DumpReportsService.java:235) at fft_battleground.dump.DumpScheduledTasks$1.task(DumpScheduledTasks.java:87) at fft_battleground.dump.DumpScheduledTask.run(DumpScheduledTasks.java:398) at java.base/java.util.TimerThread.mainLoop(Timer.java:556) at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by OtherBrand** [comment]
I've added some better logging to help track what's causing this error in version 1.6

**Comment by Larry-Schultz** [comment]
Shouldn't I just check for duplicate keys and fix them before doing the flip?
